name: Docker Publish

on:
  push:
    branches: [master]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/spiralp/https-dns-proxy:latest

      - name: Copy apk out of image
        run: |
          set -ex \
            && docker create --name temp ghcr.io/spiralp/https-dns-proxy:latest \
            && docker cp temp:/packages . \
            && docker rm temp

      - name: Release apk
        uses: softprops/action-gh-release@v1
        with:
          files: packages/community/x86_64/https-dns-proxy-*.apk
