name: Publish

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Delete old images
        uses: snok/container-retention-policy@v1
        with:
          image-names: ${{ github.event.repository.name }}
          cut-off: 1 second ago UTC
          timestamp-to-use: updated_at
          account-type: personal
          token: ${{ secrets.TOKEN }}
          untagged-only: true

      - name: Copy apk out of image
        run: |
          set -ex \
            && docker create --name temp ${{ steps.meta.outputs.tags }} \
            && docker cp temp:/packages . \
            && docker rm temp \
            && find ./packages/ -name '*.apk' -print0 | xargs -0 sha256sum

      - name: Release apk
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: packages/community/x86_64/https-dns-proxy-*.apk
